### ISSUE TITLE
License left unfilled

### ISSUE THREAD

**Issue by FloatingComet62** [studiousgamer/Zap#1]
Some [stuff](https://github.com/studiousgamer/Zap/blob/master/LICENSE#:~:text=Copyright%20%5Byyyy%5D%20%5Bname%20of%20copyright%20owner%5D) in the license is left blank, maybe it should be filled...

If the link doesn't highlight to the text, it's on line number 189..

**Comment by studiousgamer** [comment]
ok, thanks for mentioning it!
